spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**,/api/v1/clients/**

        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/v1/cards/**

        - id: products-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/api/v1/fixed-term-deposits/**